### PR TITLE
XIVY-4880 use adoptopenjdk instead of openjdk as base image

### PR DESCRIPTION
**Pull request by ivy-lli**

### CODE REVIEW

**Comment by alexsuter** [comment]
- What does this mean to the size of the image?
- Is it not possible to define somehow else the default font width? I think this is what the library tries to find out from the system.
- "work again". Did it worked before?

**Comment by ivy-lli** [comment]
>     * What does this mean to the size of the image?
> 
>     * Is it not possible to define somehow else the default font width? I think this is what the library tries to find out from the system.
> 
>     * "work again". Did it worked before?

- Downloaded dev image is 444MB, local built with this fix is 450MB
- Maybe... Need to research
- I don't think so. It was part of the 8-jdk image but never on the 11-jdk-slim

**Comment by alexsuter** [comment]
@ivy-cst opinion?

**Comment by ivy-lli** [comment]
I talked quickly with @ivy-cst, we were surprised that still the normal openjdk is in use in our docker images. Why not using adoptopenjdk?
In addition this problem seems not to happen with adopt, as they already install these libs.
The only thing is that the howl image grows to 473MB, but at least our layer should stay the same size.

**Comment by ivy-cst** [comment]
We may should document the change to adoptopenjdk also in an own issue for that?

**Review by alexsuter — APPROVED** [review]

**Review by ivy-cst — APPROVED** [review]

**Pull request merged**
