### PR TITLE
XIVY-10797 Make docker images open shift compatible

### PR DESCRIPTION
**Pull request by alexsuter**

### CODE REVIEW

**Comment by alexsuter** [comment]
Hello @chrira

Do you have time to check if this images are working in your openshift environment?

- I've already added the docker.io url at the top.
- I've improved the build.sh script, so that you can use it locally. Check README.md

**Comment by chrira** [comment]
Thanks for the improvements with the build.sh script!

I checked the image with this command to simulate a deployment on OpenShift:
`docker run -p 8080:8080 -u 1003 localhost/axonivy/axonivy-engine-local:10.0`

It stops with this failure:
```s
<title>Invalid Configuration Location</title>The configuration area at '/usr/lib/axonivy-engine/.eclipse/879735633_linux_gtk_x86_64/configuration' could not be created.  Please choose a writable location using the '-configuration' command line option.
```

I think that we have to use the arbitrary user id logic on the whole "/usr/lib/axonivy-engine" directory. 
E.g: 
```s
RUN chgrp -R 0 ${IVY_HOME} && \
    chmod -R g=u ${IVY_HOME}
```
This two lines could be added after line 27 and before the ADD of the entrypoint:

```s
   ...
    ln -s ${IVY_HOME}/logs /var/log/axonivy-engine && \
\
    chgrp -R 0 ${IVY_HOME} && \
    chmod -R g=u ${IVY_HOME}
```

**Comment by alexsuter** [comment]
Ok. 2nd try.


This, should not be needed. Because all files should already have as group 0. Done with the `chown` operations before.
``bash
chgrp -R 0 ${IVY_HOME}
``

This is needed. Because the 0 group does not have write access on all the necessary files.
```bash
chmod -R g=u ${IVY_HOME}
```

Your command works now on my system.

**Review by chrira — APPROVED** [review]
Looks good. Tested v 10.0 on OpenShift.

**Review by ivy-cst — APPROVED** [review]
Looks good, thanks @chrira and @alexsuter :+1: 

I would recommend a follow up story on the dev image: Do not allow writing to all folders on the engine only the really needed ones like configuration, logs, etc.
This would give us the safety that a running Axon Ivy Engine can not manipulate itself.

**Comment by alexsuter** [comment]
@ivy-cst yes. this could be a good idea!

**Comment by alexsuter** [comment]
@chrira thank you for this contribution! Really like that we are now ready out-of-the box for OpenShift environments ;)

**Pull request merged**
